### ISSUE TITLE
fix: `ReservoirLibrary::pairFor`

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-periphery#2]
Currently the library has to calculate the init code of the pair, which contains both tokens' addresses, and the bytecode of the pair itself. This is inefficient as it costs a lot of gas (~60,000 gas) to perform this calculation. See [discussion](https://github.com/vexchange/v3-periphery/pull/1#discussion_r984159837). Note that quoted gas figures are based on local running of `forge`.

Possible solutions:

1. do an external call to `GenericFactory.getPair()` 
   - first call costs at least 12000 gas 
   - total gas for a 3 hop swap: ~21000 gas (address is warm after the first call)
   - least changes, but cost the most 

2. do not make token0 and token1 `immutable` on the pairs, and change the `CREATE2` logic in factory to take in `keccak(abi.encode(token0, token1))` as salt 
   - in this way, the `create2` address can be calculated cheaply 
      - ~3000 gas for the operation
      - ~9000 gas for 3 hops
      - adds at least 3 `SLOAD`s for every mint, swap, and burn, since `token0` no longer immutable
         - besides reading the two token addresses, we need to read the precision multipliers (the two multipliers are packed into 1 storage slot) for the oracle
         - since each `SLOAD` is 1000 gas, that would be 3000 extra gas for each hop
     - total gas for a 3 hop swap: 3000 + 9000 = 12000 gas
   - need to introduce an `initialize` function for pairs instead of relying on the constructor to set things when creating the pair
   - seems to be the less complicated solution

3. change the interface of router functions to take in a list of pairs instead of calculating it 
   - retain `token0` and `token1` as `immutable`
   - make the frontend/caller provide the list of pairs instead of the router calculating pair addresses
   - for `swapVariableForExact` we can also make the frontend query and then provide the `amplification` and `precision`, so that the router doesn't have to
     - ~~that way, we avoid any external calls to factory/pairs before swapping, so we only do external calls to do the swap~~
       - actually we still need to do external calls to know which is token0 and which is token1 in the pair
         - ~6000 gas for calling `pair.token0()` and `pair.token1()`, so ~18000 gas for 3 hops
     - but in the signature of `swapVariableForExact` it has to take in an additional field (see below)
     - but this is optional, if it's too ugly we won't take in the additional field and let `getAmountsIn` handle the fetching
   - would be the most gas efficient solution out of the 3, but would require some change of logic in the router
   - would need to change the interface of router functions as such:

```solidity
function addLiquidity(
        address aTokenA,
        address aTokenB,
        uint256 aCurveId,
        uint256 aAmountADesired,
        uint256 aAmountBDesired,
        uint256 aAmountAMin,
        uint256 aAmountBMin,
        address aTo
)
```

becomes

```solidity
function addLiquidity(
        address aPair
        uint256 aAmount0Desired,
        uint256 aAmount1Desired,
        uint256 aAmount0Min,
        uint256 aAmount1Min,
        address aTo
)
```

---

```solidity
function swapExactForVariable(
        uint256 aAmountIn,
        uint256 aAmountOutMin,
        address[] calldata aPath,
        uint256[] calldata aCurveIds,
        address aTo
)
```

becomes: 

```solidity
function swapExactForVariable(
        address aTokenIn,
        uint256 aAmountIn,
        uint256 aAmountOutMin,
        address[] calldata aPairs,
        address aTo
)
```

---

```solidity
function swapVariableForExact(
        uint256 aAmountOut,
        uint256 aAmountInMax,
        address[] calldata aPath,
        uint256[] calldata aCurveIds,
        address aTo
)
```

becomes: 

```solidity
function swapVariableForExact(
        uint256 aAmountOut,
        uint256 aAmountInMax,
        address[] calldata aPairs,
        ExtraData[] calldata aExtraDatas,
        address aTo
)
```

**Comment by OliverNChalk** [comment]
`each call costs at least 12000 gas` - this doesn't seem right? It should be much less than that, only the first call should cost that much.


```
function swapExactForVariable(
        uint256 aAmountIn,
        uint256 aAmountOutMin,
        address[] calldata aPath,
        uint256[] calldata aCurveIds,
        address aTo
)
becomes:

function swapExactForVariable(
        address aTokenIn,
        uint256 aAmountIn,
        uint256 aAmountOutMin,
        address[] calldata aPairs,
        address aTo
)
```

Does this work? How will you know what token to swap in vs out if you only pass the pairs?

**Comment by xenide** [comment]
Alright so in our local forge env, I ran 

1 call to `getPair` - 12290
2 calls                    - 17832
3 calls                    - 21383 

Updated the issue description with this new data. 

For the new func sig

```solidity
function swapExactForVariable(
    address aTokenIn, <-- new argument
    uint256 aAmountIn,
    uint256 aAmountOutMin,
    address[] calldata aPairs,
    address aTo
)
```

With the new argument, we can just chain it in `aPairs` and iterate till the last pair. That will be the out token

**Comment by OliverNChalk** [comment]
Ahh got it, I like the interface change - how about you?

**Comment by xenide** [comment]
Actually something just occurred to me. Even if we pass in an array of pairs, we still need to call `pair.token0()` + `pair.token1()` for every pair, and that is 5000 gas for 1 call and 6000 gas for 2 calls. Hence, for a 3 hop swap, that would be 18000 gas for calls to figure out the `token0` and `token1`. 

So in light of this, option 2 seems like the least complicated and the most gas efficient solution.

**Comment by OliverNChalk** [comment]
Why not pass something like:
```solidity
struct SwapStep {
    IPair pair,
    IERC20 tokenOut,
    bool isOutTokenZero,
}

function swapExactForVariable(
    IERC20 startToken,
    uint256 amountIn,
    uint256 amountOutMin,
    SwapStep[] steps,
    address aTo
)
```

**Comment by OliverNChalk** [comment]
We can decide if this complexity isn't worth it for RouterV1. I think you are estimating the overhead wrong, because we are swapping on each pair I would imagine address access costing something like:

- 2600 for token0 call
- 100 for token 1 call
- 100 for swap call

So in theory we would only be saving ~200 gas by doing it this way. That said, SwapStep is easy at solidity layer (mainly a question of complexity at the website layer).
